/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkWithMeRouteImport } from './routes/work-with-me'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SunyaAiRouteImport } from './routes/sunya-ai'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookedRouteImport } from './routes/booked'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiSessionTitleRouteImport } from './routes/api/session-title'
import { Route as ApiContributorSignupRouteImport } from './routes/api/contributor-signup'
import { Route as ApiCommunitySignupRouteImport } from './routes/api/community-signup'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicAdminRecreateInclusiveRouteImport } from './routes/api/public/admin/recreate-inclusive'

const WorkWithMeRoute = WorkWithMeRouteImport.update({
  id: '/work-with-me',
  path: '/work-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SunyaAiRoute = SunyaAiRouteImport.update({
  id: '/sunya-ai',
  path: '/sunya-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookedRoute = BookedRouteImport.update({
  id: '/booked',
  path: '/booked',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionTitleRoute = ApiSessionTitleRouteImport.update({
  id: '/api/session-title',
  path: '/api/session-title',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContributorSignupRoute = ApiContributorSignupRouteImport.update({
  id: '/api/contributor-signup',
  path: '/api/contributor-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunitySignupRoute = ApiCommunitySignupRouteImport.update({
  id: '/api/community-signup',
  path: '/api/community-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminRecreateInclusiveRoute =
  ApiPublicAdminRecreateInclusiveRouteImport.update({
    id: '/api/public/admin/recreate-inclusive',
    path: '/api/public/admin/recreate-inclusive',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/booked': typeof BookedRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/philosophy': typeof PhilosophyRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sessions': typeof SessionsRoute
  '/sunya-ai': typeof SunyaAiRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/work-with-me': typeof WorkWithMeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/community-signup': typeof ApiCommunitySignupRoute
  '/api/contributor-signup': typeof ApiContributorSignupRoute
  '/api/session-title': typeof ApiSessionTitleRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/admin/recreate-inclusive': typeof ApiPublicAdminRecreateInclusiveRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/booked': typeof BookedRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/philosophy': typeof PhilosophyRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sessions': typeof SessionsRoute
  '/sunya-ai': typeof SunyaAiRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/work-with-me': typeof WorkWithMeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/community-signup': typeof ApiCommunitySignupRoute
  '/api/contributor-signup': typeof ApiContributorSignupRoute
  '/api/session-title': typeof ApiSessionTitleRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/admin/recreate-inclusive': typeof ApiPublicAdminRecreateInclusiveRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/booked': typeof BookedRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/philosophy': typeof PhilosophyRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sessions': typeof SessionsRoute
  '/sunya-ai': typeof SunyaAiRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/work-with-me': typeof WorkWithMeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/community-signup': typeof ApiCommunitySignupRoute
  '/api/contributor-signup': typeof ApiContributorSignupRoute
  '/api/session-title': typeof ApiSessionTitleRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/admin/recreate-inclusive': typeof ApiPublicAdminRecreateInclusiveRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/booked'
    | '/dashboard'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/philosophy'
    | '/privacy'
    | '/reset-password'
    | '/sessions'
    | '/sunya-ai'
    | '/terms'
    | '/vision'
    | '/work-with-me'
    | '/api/chat'
    | '/api/community-signup'
    | '/api/contributor-signup'
    | '/api/session-title'
    | '/checkout/return'
    | '/api/public/admin/recreate-inclusive'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/booked'
    | '/dashboard'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/philosophy'
    | '/privacy'
    | '/reset-password'
    | '/sessions'
    | '/sunya-ai'
    | '/terms'
    | '/vision'
    | '/work-with-me'
    | '/api/chat'
    | '/api/community-signup'
    | '/api/contributor-signup'
    | '/api/session-title'
    | '/checkout/return'
    | '/api/public/admin/recreate-inclusive'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/booked'
    | '/dashboard'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/philosophy'
    | '/privacy'
    | '/reset-password'
    | '/sessions'
    | '/sunya-ai'
    | '/terms'
    | '/vision'
    | '/work-with-me'
    | '/api/chat'
    | '/api/community-signup'
    | '/api/contributor-signup'
    | '/api/session-title'
    | '/checkout/return'
    | '/api/public/admin/recreate-inclusive'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BookedRoute: typeof BookedRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PhilosophyRoute: typeof PhilosophyRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionsRoute: typeof SessionsRoute
  SunyaAiRoute: typeof SunyaAiRoute
  TermsRoute: typeof TermsRoute
  VisionRoute: typeof VisionRoute
  WorkWithMeRoute: typeof WorkWithMeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCommunitySignupRoute: typeof ApiCommunitySignupRoute
  ApiContributorSignupRoute: typeof ApiContributorSignupRoute
  ApiSessionTitleRoute: typeof ApiSessionTitleRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicAdminRecreateInclusiveRoute: typeof ApiPublicAdminRecreateInclusiveRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-with-me': {
      id: '/work-with-me'
      path: '/work-with-me'
      fullPath: '/work-with-me'
      preLoaderRoute: typeof WorkWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunya-ai': {
      id: '/sunya-ai'
      path: '/sunya-ai'
      fullPath: '/sunya-ai'
      preLoaderRoute: typeof SunyaAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booked': {
      id: '/booked'
      path: '/booked'
      fullPath: '/booked'
      preLoaderRoute: typeof BookedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-title': {
      id: '/api/session-title'
      path: '/api/session-title'
      fullPath: '/api/session-title'
      preLoaderRoute: typeof ApiSessionTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contributor-signup': {
      id: '/api/contributor-signup'
      path: '/api/contributor-signup'
      fullPath: '/api/contributor-signup'
      preLoaderRoute: typeof ApiContributorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/community-signup': {
      id: '/api/community-signup'
      path: '/api/community-signup'
      fullPath: '/api/community-signup'
      preLoaderRoute: typeof ApiCommunitySignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/recreate-inclusive': {
      id: '/api/public/admin/recreate-inclusive'
      path: '/api/public/admin/recreate-inclusive'
      fullPath: '/api/public/admin/recreate-inclusive'
      preLoaderRoute: typeof ApiPublicAdminRecreateInclusiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BookedRoute: BookedRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PhilosophyRoute: PhilosophyRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionsRoute: SessionsRoute,
  SunyaAiRoute: SunyaAiRoute,
  TermsRoute: TermsRoute,
  VisionRoute: VisionRoute,
  WorkWithMeRoute: WorkWithMeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCommunitySignupRoute: ApiCommunitySignupRoute,
  ApiContributorSignupRoute: ApiContributorSignupRoute,
  ApiSessionTitleRoute: ApiSessionTitleRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicAdminRecreateInclusiveRoute: ApiPublicAdminRecreateInclusiveRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
